repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.26.3
  hooks:
    - id: check-github-workflows

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt
  - id: go-imports
  - id: no-go-testing
  - id: golangci-lint
