name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  MAIN_PYTHON_VERSION: '3.12'

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r doc/requirements.txt

      - name: Generate Go autodoc
        run: |
          cd doc/source
          python3 go_autodoc.py

      - name: Build Sphinx documentation
        run: |
          cd doc
          sphinx-build -b html source _build/html

      - name: Build GoPages API reference
        run: |
          go install github.com/johnstarich/go/gopages@latest
          gopages -internal -source-link "https://github.com/ansys/aali-sharedtypes/blob/main/{{.Path}}{{if .Line}}#L{{.Line}}{{end}}"

      - name: Integrate API reference
        run: |
          python pkg/scripts/doc_api_reference.py ansys aali-sharedtypes

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/_build/html'

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/docs'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4